nelmio_cors:
    paths:
        '^/api':
            allow_origin:  ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            expose_headers: ['Link']
            max_age: 3600
            allow_credentials: true
